### ISSUE TITLE
Separate BaseSprite's behaviors

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#104]
Currently, renderable tries to render _every_ object.

It has been suggested that we separate more of the behaviors of BaseSprite, specifically separating between Renderables and non-rendering GameObjects.

At the current point, the library could handle this separation, so it largely comes down to if this is better for end users.

If anyone has opinions or ideas, please chime in.

**Comment by astronouth7303** [comment]
Kinds of game objects include:

* Evented: Can receive events
* Positioned: Has a position
* Sized(Positioned): Has a size (implies a position)
* Physical(Sized): Participates in physics (collisions)
* Renderable (in Text, Image, and Canvas forms): Is displayed on-screen
* Container: May contain other game objects

The current `BaseSprite` is Evented, Sized, potentially Renderable:Image, and potentially Physical. Scenes are Evented and Containers. Cameras are Sized.

**Comment by astronouth7303** [comment]
Closing this due to #357
