### ISSUE TITLE
Camera point_in_viewport function incorrect

### ISSUE THREAD

**Issue by MyEyes** [ppb/pursuedpybear#109]
https://github.com/ppb/pursuedpybear/blob/master/ppb/camera.py#L73
The function checks the position in local, but the width in camera coordinates.
Should probably be:
`return vpx <= px <= vpw+vpx and vpy <= py <= vph+vpy`

**Comment by pathunstrom** [comment]
We don't have a test for this because we don't yet support multiple viewports. We can fix this code and add the tests when they're added to the API

**Comment by pathunstrom** [comment]
@astronouth7303 Yes. That's what the ticket is saying, I'm confirming, but the only thing the engine currently supports is vpx == 0 and vpy == 0.
