### ISSUE TITLE
Should an attribute that looks like an event handler always be callable?

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#116]
@ironfroggy [pointed out that we're allowing something that could be considered confusing.](https://github.com/ppb/pursuedpybear/pull/114#discussion_r218671226)

The question is valid and I am not necessarily pressed to either direction. So for anyone who feels they have a preference, present your reasoning, let's consider this.

**Comment by astronouth7303** [comment]
I'm leaning towards we should accept anything that's callable and log an error if it's not callable.

It does not need to be a class-defined method.

**Comment by astronouth7303** [comment]
There's been no discussion in 6mo. I think this should be closed.

**Comment by astronouth7303** [comment]
I'm closing this on the basis of "this is how dynamic typing works."
