### ISSUE TITLE
BaseSprite.position = (x, y) does not maintain position as a Vector

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#120]
Currently, if you assign a tuple, it will overwrite the stored value, which is a ppb.Vector. Let's fix that:

- [ ] Write a test that assigns a tuple to `Sprite.position` that fails after assignment if `Sprite.position` is not a Vector instance.
- [ ] Run the tests to confirm it fails!
- [ ] Move `Sprite.position` to `Sprite._position`
- [ ] Add a property called `position` that returns `Sprite._position`. Don't forget type hints!
- [ ] Add a setter called `position` that takes a Sequence and stores a Vector in `Sprite._position`.
- [ ] Run the tests! If it passes, you're good: Open a PR! (Don't forget to reference this issue in the PR description!)

Previous text:
> I think the right response to this problem is to add a property to BaseSprite to do the conversion for you. Then end users can get most of the benefits of the ppb.Vector class without worrying about instantiation.

**Comment by astronouth7303** [comment]
I would say do the coercion for them, otherwise you're assigning to one property and reading from another.

Or, you could make the vector coerced property assignable, but then why have the original property?

It's not very pythonic, though...

**Comment by astronouth7303** [comment]
I had a thought on this: Since we have a bunch of properties like this, would it make sense to make it a descriptor? eg:

```python
class Sprite:
    postion: Vector = typedproperty(cast=Vector.convert)
```

**Comment by pathunstrom** [comment]
Going to close this in favor of #234.
