### ISSUE TITLE
Convert engine to Pyglet

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#122]
@pathunstrom and I have been discussing this privately, but basically:

* PyGame is difficult to install across platforms
* SDL1 is architecturally flawed, and PyGame inherits those flaws

[Pyglet](https://pyglet.readthedocs.io/)

* Is pure python and installable from pip on CPython and PyPy3 with no system libraries
* Is event based through and through, architecturally aligning with PPB
* Has options for improving PPB going forward (GL2, GL3, [Pyglet's sprite engine](https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/modules/sprite.html), [Pyglet's animation support](https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/programming_guide/image.html#animations), [resource support](https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/programming_guide/resources.html))

We both have some idea how to adapt PPB's internals to Pyglet without affecting public APIs.

**Comment by astronouth7303** [comment]
There is some discussion about the utility of using the [`pyglet.clock`](https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/programming_guide/time.html) module. Piper thinks that it'll have too much jitter/drift. I hold that we should worry about that when it's evident it's a problem, since there's a pile of other things that need to be done besides a scheduler.

**Comment by astronouth7303** [comment]
On the subject of event loops, I see a few reasonable options:
* Ignore Pyglet's loop and poke pyglet the right ways from a subsystem
* Implement `GenericEngine` and `PygletEngine` with the appropriate loop
* Abstract the loop from the `GameEngine` and make generic and pyglet event loop implementations (not through the subsystem interface)

**Comment by jamesBrosnahan** [comment]
@astronouth7303 Please make a listing of features that are being used from pygame and their equivalent in pyglet so a comparison can be made? 

Also, how do you feel about writing a subsystem in cpython that interfaces directly to hardware? or making ppb capable of interfacing with multiple subsystems?

**Comment by astronouth7303** [comment]
To answer the first question, the short answer is: Everything pygame can do, pyglet can do better. A complete analysis of the two engines and their relative strengths and flaws are outside the scope of a GitHub issue.

As to why we don't just skip engines and do our own thing? I don't think anyone wants to become an expert on the multimedia APIs (graphics, sound, input) of three systems, especially when so many projects already exist to do that.

**Comment by pathunstrom** [comment]
pyglet is only one of the alternatives under consideration, but we are not staying connected to pygame indefinitely. While the project is important (and helped get this programmer into their career), we are only using it as SDL bindings and will either switch to more pure SDL bindings or move to some OpenGL alternative.

**Comment by jamesBrosnahan** [comment]
@pathunstrom Do you intend to switch to Py-SDL2 or pysdl2-cffi?

**Comment by astronouth7303** [comment]
Also up for debate is one of the SDL2 wrappers. There's pros and cons to both of these.

**Comment by astronouth7303** [comment]
Closing in favor of #197.
