### ISSUE TITLE
Add Mock Engine

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#123]
To be able to run automated tests, create a mock engine that basically takes events on one side and produces a render tree on the other.

This allows for automated testing of higher-level structures and mechanisms.

**Comment by astronouth7303** [comment]
This also implies maintaining multiple engines and being able to select one at run time.

**Comment by astronouth7303** [comment]
Is this still a thing that needs work under the current model?

**Comment by pathunstrom** [comment]
I think we still want something like this. I'm encountering the problem of having to replace the systems while working on #263 and it'd be nice to have an off the shelf option for testing that we know won't invoke a graphical context on accident.

**Comment by astronouth7303** [comment]
It'll become less of a thing as the engine becomes just the event loop?

**Comment by astronouth7303** [comment]
Ok, How are we feeling about this?

The current engine is just responsible for the event loop, system spin-up/down, and the scene stack. Its list of systems is very configurable.

The original idea could be implemented by a `MockGraphics` system.

**Comment by pathunstrom** [comment]
Yeah, at this point, we basically don't need to mock the engine proper.
