### ISSUE TITLE
Game Object hooking/registration

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#124]
Upcoming work will require engines/subsystems to be able to hook game objects:

* A pyglet-based engine would much prefer being directly notified of object changes instead of having to scan the object tree each frame
* If the sound system's primary interface is through scenes and objects (eg, object.emit_sound(), scene.start_music()), this needs to be sent back to the appropriate subsystem in order to actually play the sound. (This interface is my preference because, to me, it feels like the right abstraction, and easily handles things like stereo/spatial sound entirely within the engine with no complication from the user.)

A few options:
* Override the game object constructor to return a subclass
* Have `BaseSprite.__init__()` make a call to the engine (which is delegated to the subsystems)
* When the game object is added to the scene, have the scene call up the tree

**Comment by pathunstrom** [comment]
The game objects and scenes communicate with the sound system through events.

Loose example:

```python
class MySprite(BaseSprite):
    def play_sound(signal):
        signal(Sound(name_of_sound))
# This is not a firm API
```

The great news is if the sound system doesn't work, this is just silently ignore and minimizes coupling with the subsystems.

Other than that, I agree that hooks into BaseSprite are a good idea.

**Comment by astronouth7303** [comment]
I am actually mildly concerned with the amount of communication through events? Every event fired triggers a full tree walk, which happens twice each frame and once each tick.

Probably not a big deal at the scale most of this stuff is working at, though.

**Comment by pathunstrom** [comment]
It shouldn't be that much, but that's a note:

For events that are specifically messages to a single object, we should have some feature to kill the publish early. So the idea of a PlaySound event can be captured early in the publishing step (since the publish order is engine, engine systems, scene, and scene objects) and the we can squelch it for the rest of the tree.

Not sure how best to handle that, but it's a thing we could do.

**Comment by astronouth7303** [comment]
Maybe some kind of IOC/DI framework would be better?

**Comment by astronouth7303** [comment]
I'm going to close this as there's been a lot of external discussion, and this no longer feels relevant.
