### ISSUE TITLE
Hierarchical Game Objects

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#128]
A thing we'll need to solve eventually because if we don't end users are going to make them anyway.

**Comment by astronouth7303** [comment]
Should this include a Unified Tree Model for game objects?

**Comment by astronouth7303** [comment]
I feel like we strongly need a unified interface for game object containers.

Note that this doesn't mean that individual classes can't apply their own opinions or provide additional interfaces (eg, a `Scene` might contain a lot of things, but it can provide `.camera` and `.sprites` views into that).

**Comment by astronouth7303** [comment]
Ok, so we've discussed a lot of different aspects of this.

What do we actually want to do for 0.6?

**Comment by astronouth7303** [comment]
Ok, so a semi-concrete proposal. This should be considered a draft, and several of the aspects are not consistent with each other. Take all code as more conceptual than complete.

* Have individual collections that store the children. Using classes define these collections declaratively with property descriptors, including some kind of filter for what can be added to each collection.
* Define a `Node` mixin that defines utilities to present a virtual unified interface to all of these collections.

Conceptual usage:

```
class Scene(Node):
    sprites = ChildrenPile(type=Sprite)
    camera = SingleChild(type=Camera)
```

Draft class:

```
class Node:
    def _child_collections(self) -> Iterator[ChildCollection]:
        for name in dir(self):
            attr = getattr(self, name)
            if isintance(attr, ChildCollection):
                yield attr

    def __children__(self) -> Iterator:
        for collection in self._child_collections():
            yield from collection

    def __event_targets__(self) -> Iterator[EventMixin]:
        yield from self.__children__()

    def add(self, obj, **kwargs):
        for collection in self._child_collections():
            try:
                collection.add(obj, **kwargs)
            except Exception:
                continue
            else:
                break
        else:
            raise ValueError(f"Child {obj!r} has no valid collection in {self!r}")

    def query(self, **kwargs):
        for collection in self._child_collections():
            try:
                yield from collection.query(**kwargs)
            except Exception:
                continue
 ```

I think this will produce comprehensible pieces: 
* It's pretty understandable what children a given class can have and the semantics of each of those groups (eg, 1 camera, a stack of scenes, etc)
* Each collection has clear semantics
* Each collection has a minimal interface allowing for unification (must be iterable and inherit from a specific class) while allowing for customizations (`SingleChild` will act as an object proxy, `ChildrenStack` has additional push/pop methods, `SceneStack` can only return the top-most scene for events, `SystemPile` can assist in System's context management, etc)
* All nodes have an interface presenting the collections together as a single group (either via methods on the node or a special `children` virtual collection)

Game-specific usage:

```
class Player(Sprite)
    items = SizedChildrenPile(type=Item, size=9)
```

Additional possible features:
* Catch-all collection for if a child doesn't fit in any of the explicit collections?
* Allow each collection to define which of its members should be considered for event delivery?

**Comment by astronouth7303** [comment]
Oh, also: I expect a little big of magic for turning classes into construct-on-first-use property descriptors.

**Comment by pathunstrom** [comment]
I like the idea. Let's get an implementation done either in the engine/subsystem part or scene/sprites part. We can do the other half if it proves fruitful.

**Comment by AstraLuma** [comment]
Has this been superseded by #492 ?

**Comment by pathunstrom** [comment]
Yes, going to close in favor of the detail there.
