### ISSUE TITLE
Add button aliases to MouseMotion

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#132]
Add aliases to `ppb.events.MouseMotion` for the primary/secondary/tertiary buttons (normally: Left, right, and middle).

**Comment by pathunstrom** [comment]
Going to say if we just add the mouse object to the mouse motion events, we don't need these anymore.

Might be the better solution.

**Comment by pathunstrom** [comment]
Yeah. I'm having thoughts about the entire pattern, and we may just. . . remove the mouse system and let users just rely on the motion events.
