### ISSUE TITLE
Inter-scene data sharing?

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#136]
Should there be a mechanism to pass data between scenes?

For example, if you have a dialog scene (eg, options, saving), should the "calling" scene be able to pass it arguments, and should it be able to pass data back?

**Comment by astronouth7303** [comment]
The big problem with this is that you can't instantiate a `Scene` before handing it off; you can only hand off the class.

I suppose you could do some dynamic class/factory wrapper stuff.

**Comment by pathunstrom** [comment]
You can't instantiate it, but the dictionary you hand off in Scene.change can include `*args` and `*kwargs` which can provide rudimentary data sharing initially.

Eventually some feature to plug data into a semi-persistent place makes sense. Useful at the very least for something like top scores.

**Comment by astronouth7303** [comment]
Is the "can't instantiate it" by design (and a good one) or just how it happened?

Should we be encouraging game developers to be implementing their own `.change()`?

**Comment by astronouth7303** [comment]
The new scene change API makes it much easier to pass data into scenes (since you can directly construct a scene now).

What's the best way to return data? Register a callback? Have it raise a special event?

**Comment by astronouth7303** [comment]
Ok, my two ideas:

Callback:

```
class MyDialog(DialogScene):
    ...

class MainScene(BaseScene):
    def button_pressed(self, signal):
        signal(StartScene(MyDialog(reply=self._dialog_finished)))
    def _dialog_finish(self, data, signal):
        ...
```

Event:

```
class MyDialog(DialogScene):
    ...

class MyDialogFinished:
    ...

    def button_pressed(self, signal):
        signal(StartScene(MyDialog))
    def on_my_dialog_finished(self, event, signal):
        ...
```

(I'm also not against introducing the concept of events targeted at specific receiver, which would modify the above to be `signal(StartScene(MyDialog(reply=self))`.)

**Comment by astronouth7303** [comment]
I'm ok with closing this now; you can pass arguments into scenes now.
