### ISSUE TITLE
Make examples from pygame easy to implement in ppb.

### ISSUE THREAD

**Issue by jamesBrosnahan** [ppb/pursuedpybear#139]
Make the example code from the [pygame repository examples folder](https://github.com/pygame/pygame/tree/master/examples) easy to implement in ppb so, that users can have something to use as a first time tutorial and to make ppb extend the features of pygame better.

**Comment by astronouth7303** [comment]
> Reimplement all of the pygame examples in ppb.

Did I read that right?

**Comment by jamesBrosnahan** [comment]
@astronouth7303 Yes, you read that right. The glcube.py, midi.py, and sound.py examples are interesting demonstrations of features that can be used for education.

**Comment by astronouth7303** [comment]
* ppb is a 2D engine and it's never been a project goal to support 3D objects of any kind.
* Sound is just flat not implemented yet.
* Even when sound is implemented, I'm not sure if MIDI will ever be a thing we want.

**Comment by astronouth7303** [comment]
I'm going to close this as "reimplement pygame" nor "reimplement pygame examples" are not explicit goals, this is not a useful thing to have in our bug tracker.

We are, of course, open to additional examples. But I'm hoping a lot of what this bug really gets at (we need more examples) will be covered in future documentation and tutorial work.
