### ISSUE TITLE
Class Attrs and unified __init__

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#148]
1. Allow most attributes to be set at the class level, enabling more subclasses to be declarative or semi-declarative in nature
2. Adjust the initialization of game objects so that their `**kwargs` map to instance attributes, allowing to set instance values when creating the object.

Together with a good utility/mixin library, complex behaviors can created just by combining the right mixins and setting some class variables (and maybe defining a method or two).

**Comment by astronouth7303** [comment]
#133 is in this vein, and has some discussion on this topic.

**Comment by astronouth7303** [comment]
This has been done for scenes and sprites. Do any other objects need the treatment?

**Comment by pathunstrom** [comment]
Completed with fba0db2ad825a99e4bec37ed52ce9d7438aa267c
