### ISSUE TITLE
Dataclass error when trying to run examples with python 3.6.6

### ISSUE THREAD

**Issue by crazcalm** [ppb/pursuedpybear#149]
I did the pip install.

![pip_install_ppb](https://user-images.githubusercontent.com/3482344/46426695-59ce6180-c70d-11e8-8b27-2bbbb42985b6.png)

The setup.py file does have a line about back porting data classes, but I got the following error when I tried to run an example.

![ppb_dataclaasses_error](https://user-images.githubusercontent.com/3482344/46426702-5cc95200-c70d-11e8-987c-965a5b847357.png)

Was there anything I was suppose to do in order to make sure data classes were back ported?

Note: I am running the Ubuntu Mate system install of Python 3.6.6

**Comment by astronouth7303** [comment]
Umm.... No, it's supposed to install it if you have a version before 3.7, no additional intervention needed.

**Comment by astronouth7303** [comment]
Umm.... No, it's supposed to install it if you have a version before 3.7, no additional intervention needed.

**Comment by astronouth7303** [comment]
I also got this report on macOS majove.

**Comment by astronouth7303** [comment]
I can reproduce this when installing from the system Python. I am not able to reproduce this when a virtual environment is active.

**Comment by astronouth7303** [comment]
Wheels.

`setup.py` computes dependencies based on runtime version (Python 3.6 has a different set of dependencies than Python 3.7). However, we only publish one wheel with one set of dependencies, to be used by both Pythons.

**Comment by crazcalm** [comment]
@astronouth7303 I saw your pull request. I do not know a good way of testing that either. In any case, thank you for looking into this!
