### ISSUE TITLE
Error when running framcount.py example

### ISSUE THREAD

**Issue by crazcalm** [ppb/pursuedpybear#151]
Error:

       Traceback (most recent call last):
          File "framecount.py", line 18, in <module>
            from ppb.event import Tick, Quit
        ModuleNotFoundError: No module named 'ppb.event'

After a quick check, it seems like Tick no longer exists in the ppb.event.py file. 

I am not sure how you guys want to proceed with this.

**Comment by astronouth7303** [comment]
The examples need updating. Sorry about that.

I wrote some stuff of my own at https://gitlab.com/astronouth7303/mutant-games
