### ISSUE TITLE
In REPL, import ppb gave me pygame information

### ISSUE THREAD

**Issue by crazcalm** [ppb/pursuedpybear#166]
Am I suppose to be seeing this? 

    Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
    [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ppb
    pygame 1.9.4
    Hello from the pygame community. https://www.pygame.org/contribute.html

**Comment by pathunstrom** [comment]
Yeah, pygame is currently _not_ being a good citizen. I've got a hack around it in a working branch somewhere, but for now there's nothing I can do that doesn't cause more problems than just ignoring it.

**Comment by jamesBrosnahan** [comment]
Should an issue report be created in the pygame repository for this?

**Comment by pathunstrom** [comment]
If users of Pygame find it bothersome, they can report it. I'm not going to organize that though.

**Comment by astronouth7303** [comment]
Closing based on the lack of activity, and the lack of our ability to do anything about it.
