### ISSUE TITLE
Resource path extension breaks

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#167]
If you override resource_path you get the following error, stack trace anonymized:

```
Traceback (most recent call last):
  File "scratch.py", line 11, in <module>
    run(scene_kwargs={"set_up": setup})
  File ".venv/lib/python3.7/site-packages/ppb/__init__.py", line 13, in run
    eng.run()
  File ".venv/lib/python3.7/site-packages/ppb/engine.py", line 78, in run
    self.main_loop()
  File ".venv/lib/python3.7/site-packages/ppb/engine.py", line 92, in main_loop
    self.publish()
  File ".venv/lib/python3.7/site-packages/ppb/engine.py", line 113, in publish
    entity.__event__(event, self.signal)
  File ".venv/lib/python3.7/site-packages/ppb/events.py", line 62, in __event__
    meth(bag, fire_event)
  File ".venv/lib/python3.7/site-packages/ppb/systems.py", line 149, in on_render
    resource = self.prepare_resource(game_object)
  File ".venv/lib/python3.7/site-packages/ppb/systems.py", line 164, in prepare_resource
    self.register_renderable(game_object)
  File "/.venv/lib/python3.7/site-packages/ppb/systems.py", line 191, in register_renderable
    self.register(source_path / image_name, image_name)
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

Here's the minimum sample to reproduce:

```python
from ppb import BaseSprite, run


class Player(BaseSprite):
    resource_path = "./resources/"


def setup(scene):
    scene.add(Player())

run(scene_kwargs={"set_up": setup})
```

```
$ python --version
Python 3.7.0
```

**Comment by dillonko** [comment]
I get a different error:

```
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "game_issue.py", line 9, in <module>
    run(scene_kwargs={"set_up": setup})
TypeError: run() got an unexpected keyword argument 'scene_kwargs'
```

```
$ python --version
Python 3.7.1
```

**Comment by astronouth7303** [comment]
I think this is part of the bigger problem that we want typed properties (see also: assigning tuples to position)

**Comment by pathunstrom** [comment]
This one is more on the protocol side. We want it to take a string, but it needs to be transformed to a Path in the protocol to work the way we intend.

**Comment by dillonko** [comment]
Can you give me more insight on that. It will be easier to execute if I
know what your goal is.

I think I know where you are going with it, but don't want to make any
asummtions.

**Comment by astronouth7303** [comment]
We define a few dunder methods for dealing with resources. BaseSprite has default implementations of them that either return attributes or a computed default.

(These dunder methods are where ppb-mutant hook, for an alternate implementation.)

**Comment by dillonko** [comment]
Ok I will take some time and get head around it.

**Comment by dillonko** [comment]
I don't see the path to the player file. I was able to get the issue resolved locally on my end.

**Comment by pathunstrom** [comment]
https://github.com/ppb/pursuedpybear/blob/master/ppb/sprites.py#L237-L240

Here's the relevant function.

**Comment by dillonko** [comment]
ok cool thanks looking at it now.

**Comment by astronouth7303** [comment]
Obsoleted by #306

**Comment by astronouth7303** [comment]
Closing this because the resource path concept is no more.
