### ISSUE TITLE
International keycodes

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#173]
There are about a dozen major layouts internationally, each with its own set of base and shifted keys.

Add support for layouts besides QWERTY/USA.

**Comment by pathunstrom** [comment]
This might be more complicated that it looks, we're going to close for now. If anyone outside of the QWERTY layout wants to provide maps to help with this, feel free, but it's not a thing we're going to actively solve at this time.

Keycodes are specifically the physical position of the key. We don't use keycodes, we provide a key mapping.

This is not for text, it's for keyboard input.
