### ISSUE TITLE
Change the various camera relationships.

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#185]
Currently, frame width and height are derived from the viewport size and the pixel ratio. This makes calculating what counts as _in_ much harder for the end user.

The viewport should have a screen origin, a percentage of the screen it occupies in each axis, and knowledge of the resolution. It then derives it's width and height from these factors.

The frame should have a width and a height. It should have a method available for forcing the frame aspect ratio to match the viewport aspect ratio, which can be called when any of the root values is changed: the sceen percentages, the resolution, or the frame width (Or frame height in the case that a user sets the zoom using it.)

**Comment by astronouth7303** [comment]
A feel like some of these terms need to be well-defined?

I understand what a window is (a space the OS gives us to exist in, may have more than one depending on _things_), but it's not super clear what viewports and frames are and how they relate to the window.
