### ISSUE TITLE
Add magic method to convert a side to an int.

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#193]
I want to truncate the value of a side. `int(Sprite.left))` should be a meaningful operation.

Similarly `round()` should work.

**Comment by astronouth7303** [comment]
This should just be adding `__int__()` and `__float__()`, right?

**Comment by pathunstrom** [comment]
And `__round__` apparently. I was loosely researching it last night.

I might actually break this out and make three separate issues for this. Those should all be implemented, and it's low hanging fruit for new contributors.

**Comment by astronouth7303** [comment]
By that logic, we should implement the entire `numbers.Real` interface as well, so that various operations work directly.

**Comment by pathunstrom** [comment]
Maybe. I know I need `round` and `int`. `float` is useful. `ceiling` and `floor` are potentially useful.

**Comment by astronouth7303** [comment]
It's hard to say how it'll be used?

`player.position = (left_sprite.right + right_sprite.left) / 2` to center something.

**Comment by pathunstrom** [comment]
```
left_square = update.scene.play_grid.get((round(self.left.value), self.position.y))
right_square = update.scene.play_grid.get((round(self.right.value), self.position.y))
```

I was using a basic spatial hash to find collisions in a game I built.

**Comment by astronouth7303** [comment]
Why the `round()` call? we're talking game units, not pixels.

**Comment by pathunstrom** [comment]
Because the squares were stored in a dictionary with an `Tuple[int, int]` key based on their position.

**Comment by astronouth7303** [comment]
Ummm... is it possible having a numeric type with a mutable value might be problematic?

**Comment by astronouth7303** [comment]
Like, we could throw on the complete `numbers.Real` interface on `Side` and it'll be fully usable in operations, but I'm wondering if there might be problems with that?

**Comment by astronouth7303** [comment]
Ok, so, we should do one of two things:

1. Replace `.value` with `float()`
2. Implement the full `float` API
