### ISSUE TITLE
Engine Tracking Issue

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#197]
Ok, so: We've officially outgrown PyGame. Basic work with pyglet show a massive performance improvement.

For due dilligence, we should also test direct SDL2 bindings. Are there other libraries we should check?

Questions we should be asking:

* What platforms are supported?
* What is the installation story for game developers using ppb?
* What is the performance of it? relative to pygame? other candidates?
* What work does this save us?
* What additional work does this add?
* How does this affect future work: Sound? Animation? Packaging? Canvas Revolution (including text)?
* (Jamie's special interest: How does this interact with asyncio?)

**Comment by astronouth7303** [comment]
Pyglet: Basically, does everything for us.

Has sound (including spatial), has resource management (including from zip), has super-performant batch rendering. Has some kind of animation support. Has canvas support, with text rendering and stuff.

It's pure python and zip safe, so we can directly use it from zipapps without unpackagers like pyz/pants.

It supports Linux (X11), Mac, and Windows. BSD unknown. Does not support Wayland.

As a bonus, handles keycodes vs text, multiple windows.

Initial benchmarks indicate its clock is less accurate than the current ppb one. But it also uses much less CPU. (The current implementation busy-polls, leading to high CPU usage.)

**Comment by pathunstrom** [comment]
Resource management is a wishlist item right now, for when people start wanting to build bigger things and it'll be a pretty necessary tool. We're just  not there yet.

**Comment by astronouth7303** [comment]
Lets discuss the role of resource management in #147

**Comment by astronouth7303** [comment]
Updates:

* pyglet has some major crashing bugs on Mac.
* https://www.pygame.org/news/2018/11/where-we-are-up-to-with-pygame-2-and-1-9-5
* repl.it has a pygame language mode, allowing for ppb/pygame to completely run in the browser (albeit slow)

**Comment by astronouth7303** [comment]
#387 #377
