### ISSUE TITLE
Formalize non-core utilities

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#198]
We want to include a bunch of functionality that does not fall into the MVP core of "give code events, throw graphics on screen, play sounds".

This includes #81, #121, and #140.

Basically: These are all very nice things for making a game, but can all be implemented in terms of existing ppb primitives and do not require additional low-level work. They would function just as well as external packages or game code.

Let's formalize where these live and how users use them.

**Comment by astronouth7303** [comment]
My preference is a django-like contribs system where a user may elect to opt-in to each feature through various means. (mixins probably the most common?)

This has the added benefit of feeling very similar to external packages.

**Comment by astronouth7303** [comment]
Examples: Collision as mixins would probably look like:

```
class MySprite(CircularRegion):
    ...

class MyScene(CollisionIndex):
    ...

def on_stuff(mysprite, theirsprite):
    if mysprite.overlaps(theirsprite):
        # Do stuff
        ...
```

**Comment by pathunstrom** [comment]
So are you thinking `ppb.contrib` or some other name space, or `ppb-contrib` that can be an optional dependency?

(Feel free to replace contrib with ext or any other name.)

**Comment by astronouth7303** [comment]
Well, part of the pitch is "it ships with; you already have it"? Unless we want to break it up into ppb-core, ppb-contrib, and a ppb metapackage.

I guess my bigger question is if you have opinions about the name? I just cribbed contrib from Django, but they're not necessarily contributions.

**Comment by pathunstrom** [comment]
Um, I've seen `contrib`, `ext`, and `util` all used for similar things.

I don't know if I love any of them.

We could also call them `prefabs` but that's less elegant, even if it's kind of actually what we're building.

**Comment by astronouth7303** [comment]
I think I also said `features` at one point.

**Comment by pathunstrom** [comment]
I think I like that one best. I'll do some preliminary asking of some of my teacher contacts and come back on this.

**Comment by astronouth7303** [comment]
@pathunstrom Any results from asking around?

**Comment by astronouth7303** [comment]
Ok, so we're going with `features`, and the first one is #230 .
