### ISSUE TITLE
GameEngine.start_scene only instantiates if there are kwargs

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#203]
If you use the change scene events with a scene that doesn't require arguments, the engine doesn't instantiate it and instead just adds the class to the scene stack.

Minimal example:

```python
from ppb import BaseScene
from ppb import run
from ppb.events import StartScene
from ppb.events import Update

splash_length= 0.5

class Splash(BaseScene):
    background_color = (101, 78, 163)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.run_time = 0

    def on_update(self, update: Update, signal):
        self.run_time += update.time_delta
        if self.run_time >= splash_length:
            signal(StartScene(Menu))


class Menu(BaseScene):
    background_color = (50, 50, 50)

run(Splash)
```

Results in a TypeError when the scene changes.

[Relevant function.](https://github.com/ppb/pursuedpybear/blob/master/ppb/engine.py#L173-L177)

ppb version 0.5.0
python version 3.7.2
os Windows 10

**Comment by astronouth7303** [comment]
This seems important enough to make a patch release for.

**Comment by pathunstrom** [comment]
We never got on this. So I'm moving this up the priority chain.
