### ISSUE TITLE
Audit ppb wheels

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#205]
Recently learned that the build directory can cause things to happen improperly when files are removed from a project.

We should audit the existing wheels to guarantee nothing untoward is in the builds.

Also, should probably check in the build scripts I use to produce the wheels.

- [ ] Audit wheels
- [x] Check in build scripts

**Comment by astronouth7303** [comment]
They seem ok? :woman_shrugging: 

We've had new releases since this, too.
