### ISSUE TITLE
Window Title Regression

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#206]
It is no longer possible to set a window title.

**Comment by pathunstrom** [comment]
I just did it, my guess is you mean via `run`?

**Comment by astronouth7303** [comment]
That's fair.

Mostly, I don't like the amount of stuff you have to do manually the moment you stray from the prescribed `run()`. And it feels like setting a window title is simple, universal, and encouraged.

**Comment by pathunstrom** [comment]
So, I think the actual thing here is `title` should be a parameter to `run` specifically called out. (Doesn't need to be `window_title` as that's implementation detail.

Or alternatively, the parameter could just be `name` and be the name of the game you're working on?

**Comment by astronouth7303** [comment]
What other contexts are we going to be using it for?

**Comment by bildzeitung** [comment]
Looks like Render() has a `window_title` kwarg, so it seems like a reasonable fix is to add a `title` parameter to the top-level `kwargs`
