### ISSUE TITLE
Documentation regarding resource path protocol

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#212]

**Comment by astronouth7303** [comment]
Shouldn't this be part of documentation in general? A "nuts and bolts" section?

**Comment by pathunstrom** [comment]
Yes.

I put this to remind myself because I get more questions on this than any other.

**Comment by astronouth7303** [comment]
Obsoleted by #306

**Comment by astronouth7303** [comment]
Closing this because the resource path protocol is no more.
