### ISSUE TITLE
Add Test Dependencies to setup.py

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#222]
Didn't realize I hadn't done this, we should absolutely have the setup.py set up to manage test dependencies.

**Comment by astronouth7303** [comment]
To be fair, very few projects do this.

**Comment by nbraud** [comment]
@pathunstrom I'd rather have them in an easily-parsed form, and have `setup.py` read it out, as I did in https://github.com/nbraud/pursuedpybear/pull/1/commits/5eb0550896640177eaf0ea0d185d6fad66427416.  That way, it's easy to get the list of dependencies when building a test environment.

I guess this is in reaction to commit https://github.com/ppb/pursuedpybear/pull/220/commits/05e61a6b75c2242ffc74041493b037375c9b820a in #220 ?
