### ISSUE TITLE
Sprite Animations

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#24]
Probably too big as a single task. Low priority.

**Comment by ironfroggy** [comment]
Here are suggestions for making this a natural step after static sprites. Maybe these are separate issues later?

1. If you already have a `sprite.png` adding number postfixed images in the same location (`sprite-2.png`, etc.) will create an animation automatically, at the base FPS
2. If the numbers are consecutive (1, 2, 3, 4...) the animation frames run at a consistent rate. If a frame number is skipped, it indicates a pause (1, 2, 10, 11)
3. Sprite classes have an optional "Sprite FPS" attribute that customizes the frame rate of the animation associated with that sprite. For example, if the game is running at 60 FPS and the Sprite FPS is 12, each image holds for 5 game frames. Maybe there could be a game-wide default you can adjust? Dunno.

**Comment by astronouth7303** [comment]
I wrote an `AnimationSprite` in [mutant games](https://gitlab.com/astronouth7303/mutant-games/blob/master/utils.py), although this is more like a particle effect.

**Comment by jamesBrosnahan** [comment]
OpenGL uses texture coordinates to map multiple textures to a single image file. The top left of the image is index 0,0 and the bottom right is 1,1. If you have a sprite sheet like this: [fire animation sprite-sheet](https://opengameart.org/sites/default/files/styles/medium/public/fire_circles_50x50px.png) the texture coordinates for the first frame in the animation are [(0,0), (0,0.125), (0.125, 0.125), (0.125, 0)] _note: the coordinates are counterclockwise this is explained in this link [why-should-i-create-vertices-counter-clockwise-and-not-clockwise](https://stackoverflow.com/questions/20477137/why-should-i-create-vertices-counter-clockwise-and-not-clockwise) as allowing [back face culling](https://en.wikipedia.org/wiki/Back-face_culling) to be used._ In the example sprite-sheet the frames are in a 2d left-to-right array this configuration and the alternative top-down listing of frames are special cases that deserve to be programmed as presets for an animated-sprite-sheet class. 

For implementing sprite animations; I recommend creating a [dataclass](https://docs.python.org/3/library/dataclasses.html) that holds the texture coordinates, and frame number; then using a generator class to represent the animation [how-to-write-a-generator-class](https://stackoverflow.com/questions/42983569/how-to-write-a-generator-class)
`
def animation-generator(sprite-sheet, frame-number):
    //check if frame exists as an entry into the dictionary of frames
    if not dictionary-of-computed-frames[frame-number]:
        list-of-computed-frames[] = (compute-texture-coordinate-using-callback-function)    
    return dictionary-of-computed-frames[frame-number]
`

explanation of texture coordinates for uv mapping on stackoverflow: [how do opengl texture coordinates work](https://stackoverflow.com/questions/5532595/how-do-opengl-texture-coordinates-work)

**Comment by astronouth7303** [comment]
Implemented in #230.
