### ISSUE TITLE
Targeted Events

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#249]
We want to add events that get published to specific targets.

There's a discussion to be had on whether targeted events can _only_ be seen by a single target, or if we want to support multiple targets.

This change will _absolutely_ require a change to the engine itself, so is not recommended for new contributors.

**Comment by jamesBrosnahan** [comment]
Can lambdas/method references be used with the current event system to make event targets similar to C# delegates or is this different from that type of functionality?

**Comment by astronouth7303** [comment]
The exact mechanics are:

1. The engine produces a pile of potential event receivers
2. The `__event__()` is called on each receiver
3. `__event__()` handles dispatching to the local `do_*()` callable and also handles logging, error handling, etc.

We have no opinion about what kind of callable it is, but there is not currently way to add bare functions. The recommended solution would be: Wrap it in a system and add it to the engine. (#263)

**Comment by astronouth7303** [comment]
The targeted thing is meant to handle cases where you want to use the event dispatch mechanism, but you don't want it broadcast to every active object in the game tree. This might be for: The renderer informing cameras about their geometry (in multi-camera contexts), collision systems only telling the objects that collided about their collision, and possibly other uses.

**Comment by astronouth7303** [comment]
Note that this is different from #252, where the specific target is not necessarily known, but we (as engine and game designers) are fairly certain it should be handled by one object. (This is really an abuse of the event system in lieu of a DI or IOC framework.)

**Comment by pathunstrom** [comment]
Okay, so this conversation gave me some inspiration, so going to forward a proposal:

Assuming that our current model for publishing looks like this (this is how it currently works, just not explicitly):

1. Pop the next event off the queue.
2. Call the registered extensions to extend or enrich the event.
3. Publish to the targets of the event (currently, the entire tree)

The suggestion is let's add `__targets__` as part of the events API. `__targets__` will by necessity be an iterable. We then modify step three above:

3. Publish to the targets of the event: If `__targets__` exists and is not empty, we only call `__event__` on its members, otherwise, we walk the entire tree as normal.

This gives us a mechanism by which #252 can be done, and keeps exceptions in the engine at a minimum. It also allows subsystems to use the extension plumbing to define it's API event simply by modifying __targets__ on those events.
