### ISSUE TITLE
Remove Engine required parameter from BaseScene

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#254]
The engine will still pass itself as a kwarg if you use the implicit instantiation `StartScene(scene_type, kwargs)` and can be relied on, but a lot of scenes don't care and we shouldn't be required to mock the engine in testing for things that don't care.

https://github.com/ppb/pursuedpybear/blob/master/tests/test_scenes.py#L28-L30

**Comment by astronouth7303** [comment]
Implemented by #284
