### ISSUE TITLE
Extensions API

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#263]
One of the sour points of ppb right now is subsystems _are hard_ to add to the engine. You have to rebuild the `systems` kwarg to get the basic engine + your new thing.

Let's add a new kwarg that gets appended to the systems kwarg  for this use case.

We should discuss here whether that should be called `extensions` or `plugins` or something else.

- [ ] Pick a name.
- [ ] Add keyword argument `???`
- [ ] Modify engine to use new kwarg.
- [ ] Test it!
- [ ] Make sure name is in CONTRIBUTORS.md

**Comment by pathunstrom** [comment]
Thumbs up this post if you like `extensions`

**Comment by pathunstrom** [comment]
Thumbs up this post if you like `plugins`

**Comment by pathunstrom** [comment]
All other suggestions below this line. Please thumbs up if your preference is already here.

**Comment by astronouth7303** [comment]
I would use `systems` and `basic_systems`, where `systems` is the one for game developers, and `basic_systems` is pre-filled with the systems you almost certainly need to write a game.

The use case for overriding `basic_systems` is new engine backends, testing, or other wild abuses of PPB, where I trust the developer is advanced enough to understand the distinction and deal with it.

**Comment by pathunstrom** [comment]
Gonna add a second suggestion: `systems` and `core_systems`

**Comment by astronouth7303** [comment]
That's also a good suggestion.

Without further information or outside consultation, I think we've hit the point of "just pick one".
