### ISSUE TITLE
Layering (Render Order)

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#276]
At some point, we're going to need the ability to have a well-defined render order. I see a few ways to do this:

* Layers: Scenes declare layers by name and order, and sprites declare what layer they're part of
* Z axis: Sprites grow a z-index, and sprites are sorted based on their z-index
* Ordered Sprites: Sprites in a scene become ordered and are rendered in that order. Scenes grow methods to reorder sprites.

My personal opinions: Layers are semantic and meaningful, but require a bit more work in the renderer. Z axis is simple and easily nuanced, but lacks in intrinsic meaning. Ordered Sprites seems awkward to work with and would be more challenging to implement with #229.

**Comment by pathunstrom** [comment]
I've thought about adding layers as an additional index in Scenes, which can read off of a layer attribute when an object gets added or set explicitly via keyword.

Then it's a matter of ordering the output of `__iter__` to follow the layers in one order or the other.

**Comment by pathunstrom** [comment]
Which I guess is. . . both a and b combined.

**Comment by jamesBrosnahan** [comment]
How do you feel about making a layer data class that holds a z-index and
returns objects holding a reference to it. Then having a container class
that gets read from during rendering?
https://stackoverflow.com/questions/11891755/find-all-references-to-an-object-in-python
this link recommends the usage of gc.get_referrers(*objs) to find objects
references [useful if the layers should be seamless]

**Comment by pathunstrom** [comment]
@jamesBrosnahan How does that interact with the scene split? Will objects in non-active scenes end up visible if we grab _all_ references?

**Comment by jamesBrosnahan** [comment]
How do you feel about having a layer class that uses
gc.get_referrers(*objs) to look up the objects that reference a layer
during rendering?

https://stackoverflow.com/a/33398553

**Comment by jamesBrosnahan** [comment]
The layer gets read by the render loop and returns a list of references to
objects that are part of that layer. The objects then need to be processed
to determine if they should not be rendered, or the scene could own their
layer container and processing can be skipped if the scene is disabled.

**Comment by astronouth7303** [comment]
That all seems needlessly complex and brittle?

Like, to implement z-index, you just need `sprites = sorted(scene.sprites, key=lambda s: s.z_index)`

Named layers just need something like `sprites = sorted(scene.sprites, key=lambda s: scene.layers.index(s.layer))` (except not exactly, because there's more edge cases).

We don't need explicit layer objects and tracking references and stuff? Just some primitive values?

**Comment by jamesBrosnahan** [comment]
@astronouth7303 Tracking references to layers is to make it easier to abstract the layers from the game objects and allows methods like these `print(layer_1.objs_on_layer())` and `layer_1.remove_objs_like_this_from_layer(obj)`. Z-indices make it difficult for new people to join game projects by creating magic numbers in code.

**Comment by astronouth7303** [comment]
> Z-indices make it difficult for new people to join game projects by creating magic numbers in code.

Fair enough, hence:

> Z axis is simple and easily nuanced, but lacks in intrinsic meaning.

> Tracking references to layers is to make it easier to abstract the layers from the game objects and allows methods like these print(layer_1.objs_on_layer()) and layer_1.remove_objs_like_this_from_layer(obj).

Fair enough, but those specific uses are easily accomplished by just filtering the sprite list (`[s for s in scene if s.layer = 'spam']`).

Tracking refs seems like it would be fragile in cases where you do anything not in the box. Like a manager juggling layers for something. Or a sprite that switches between layers and keeps refs to all of the layers it may occupy. Or a sprite that gets added/removed from a scene regularly. Or if a layer gets used between scenes and has sprites from both attached (:astonished:).

And it provides no value in implementing the renderer? Like, just sort the sprites by layer order and you're fine?

And frankly, I'm not seeing how they provide semantic meaning or usefulness above and beyond string identifiers. Maybe some day in the distant future, when we implement shaders or scene effects and some effects apply to only certain layers. But that's not even close to the roadmap.

**Comment by jamesBrosnahan** [comment]
@astronouth7303 Is there a good way to still have utility methods to manage the layers without needing individual layer class instances?

**Comment by astronouth7303** [comment]
Sure:

* Utility functions, either in a module or in the scene
* Manipulate the layer list directly
* Just touch the sprites
* Just filter the list of sprites

Like, every event handler gets the current scene, and therefore both the pile of sprites and the scene order.

**Comment by jamesBrosnahan** [comment]
@astronouth7303 

> - Utility functions, either in a module or in the scene
>- Manipulate the layer list directly

Could a type of preprocess event be triggered as the sprites are processed by the renderer that calls the utility methods needed?

**Comment by astronouth7303** [comment]
Sure, but to what end? What needs to be processed? This is literally just "define the order the sprites should to be rendered in". The problem is not that complicated, and our discussions just need to resolve:

* What are reasonable ways to do this?
* What is easiest to learn?
* What encourages best practices?
* Do any of the options preference particular styles/genres of games?
* What other considerations are there? Do they apply to PPB's use cases and goals?

Given this is a learning library maintained by volunteers. We try to make our magic tractable and easy to reason about.

**Comment by jamesBrosnahan** [comment]
@astronouth7303 
> Sure, but to what end? What needs to be processed?
A group of use cases for having post processing of layers is being able to do:
- Improving resolution of sprites before rendering [using-deep-learning-for-single-image-super-resolution](https://deepsense.ai/using-deep-learning-for-single-image-super-resolution/)
- A depth of field effect on layers [i.e. a stronger blur on the background vs foreground]
- A night-day cycle that is layer specific

**Comment by astronouth7303** [comment]
Replace the layer list with an ordered dict or list of pairs, where the value/second item is the options.

Or insert a LayerEffects object in the list of layers, where it'll apply to anything below it in the layer stack.

Anything involving "deep learning" is well outside the scope of ppb for a long, long time.

**Comment by astronouth7303** [comment]
I am exercising my moderation powers as maintainer and am officially vetoing any proposals involving `gc.get_referrers()`. It is extremely magical and without a compelling reason why magic of that magnitude is needed. All use cases presented so far have been easily refuted with significantly more mundane proposals.

In addition, I'm skeptical that any use of `gc.get_referrers()` for any use other than debugging and development exists. It is simply too fragile and too fraught with edge cases.

Any further discussion of such proposals will be removed. Further violations will lead to blocking users.

**Comment by astronouth7303** [comment]
Correction: gevent has a [legitimate use](https://github.com/gevent/gevent/blob/64ce33e5796c32d113b8b2ecf8174d0a24c482fa/src/gevent/monkey.py#L761-L786) in their monkey patching machinery. They're using it to literally find all the references that need to updated with the gevent versions.

**Comment by pathunstrom** [comment]
Resolved with #350
