### ISSUE TITLE
What do we want in 0.7?

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#277]
0.6 is coming to a close, which means we need to start discussing our next release. Since there's a _lot_ more stakeholders this time around, I'm making an explicit issue here to discuss this. This discussion will become the basis for the 0.7 project board.

If you're suggesting a topic, please put it in a separate message, and everyone who cares can vote up or vote down with a reaction.

Discussion can go between suggestions. I'll try to keep this OP up to date with all of the suggestions.

**Comment by pathunstrom** [comment]
Suggestion: Really focus on documentation

**Comment by pathunstrom** [comment]
Suggestion: Rebuild renderer to handle new rendering contexts and make layering a thing.

**Comment by astronouth7303** [comment]
Suggestion: Sound

**Comment by astronouth7303** [comment]
Suggestion: Sound

**Comment by astronouth7303** [comment]
Suggestion: Resource revamp #147

(This might also get caught up with the sound and render context work.)

**Comment by astronouth7303** [comment]
Suggestion: Regions and Physics feature #121

**Comment by astronouth7303** [comment]
Suggestion: Behavior Trees and Finite State Machines.

(I'm including this because it's been discussed as a feature, but I'm personally of the opinion we've got other fish to fry.)

**Comment by astronouth7303** [comment]
Suggestion: Subsprites and Camera-attached sprites.

Roughly, making a sprite that's a child of a sprite or a camera meaningful.

**Comment by astronouth7303** [comment]
Suggestion: Stacking scene rendering with alpha backgrounds. #143

**Comment by astronouth7303** [comment]
Suggestion: Gamepad support

**Comment by astronouth7303** [comment]
Suggestion: Actions feature

**Comment by nbraud** [comment]
> Regions and Physics feature

@astronouth7303 What do you mean by `Regions` there?
In any case, I would be pretty keen on having a stab at a declarative-ish thing for specifying dynamics.

**Comment by astronouth7303** [comment]
Ok, so here's what I'm seeing based on this:

* Docs
* Resource/asset rewrite
* Sound

**Comment by pathunstrom** [comment]
How long do you think a prototype of your imagining for resources/assets be?

Since Sound is going to need to lean on it somehow.

**Comment by astronouth7303** [comment]
I've already done the initial prototypes. Need to round it out into a data model integrated with the ppb system.

**Comment by astronouth7303** [comment]
Closing in favor of https://github.com/orgs/ppb/projects/7
