### ISSUE TITLE
Key Repeating?

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#291]
So, apparently some uncommon setups will produce multiple `KeyPressed` events before their matching `KeyReleased` event.

I feel like we should filter these? `KeyPressed`/`KeyReleased` are meant to be fairly direct: they are indicators of the physical keys and aren't suitable for text processing. (Key repeating is a standard thing in text contexts.)

If holding a key repeats an action, that should be a thing controlled by the game (since it's a game balance knob). It also can cause bugs in code not expecting it (eg, the key->motion code in our demos).

**Comment by astronouth7303** [comment]
Again, key repeating:

* Text input: :+1: 
* Game controls: :-1:

**Comment by pathunstrom** [comment]
I guess, historical note: The old school [NES Advantage](https://en.wikipedia.org/wiki/NES_Advantage) had a turbo button that did this. It's just a feature some keyboard and input devices have and I'd rather not futz with end user expectations by filtering their input.

**Comment by astronouth7303** [comment]
Wait, did they just smash a virtual key while still properly sequencing events? Or is there a problem where pressed and released events aren't properly paired?

**Comment by pathunstrom** [comment]
In my experience with key repeats causing issues in PyGame: They aren't paired.

**Comment by astronouth7303** [comment]
Yeah, it's not that I want to disable key repeating or accessibility stuff, I just want to make sure the events are properly paired.

**Comment by astronouth7303** [comment]
Closing this as the assumption is that text input will be a whole other set of events.
