### ISSUE TITLE
ppb sprite subclasses cannot be defined in Jupyter notebooks

### ISSUE THREAD

**Issue by moshez** [ppb/pursuedpybear#300]
See notebook at https://github.com/moshez/ppb-issue/blob/master/ppb-issue.ipynb (I cannot attach notebooks to tickets).

Steps to reproduce:

* Save notebook locally
* In a virtual environment, install ppb and jupyterlab
* Run `jupyter lab`
* Open the notebook from the browser
* Execute the cell

**Comment by astronouth7303** [comment]
This looks extremely similar to the problem I found with defining sprites in a repl.

This should be fixed incidentally by the asset system rebuild.

**Comment by moshez** [comment]
Is there a ticket opened for the problem you found? Happy to dup this.

**Comment by astronouth7303** [comment]
#267 and #270

I'm guessing that jupyter does something slightly different to defeat this.

**Comment by moshez** [comment]
This is fixed by #270 -- I did not update my ppb repository.

**Comment by astronouth7303** [comment]
Note: #306
