### ISSUE TITLE
Remove circular import in events.py

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#304]
Currently, there's a circular dependency issue around the `events` module:

Just about every class in `ppb` depends on `EventMixin`, but events in the events module depend on types defined elsewhere in `ppb`. We should break that.

A simple solution would be to start a `plumbing.py` or `event_mixin.py` and move `EventMixin` to the new file, leaving events with the event definitions only.

**Comment by astronouth7303** [comment]
Closing because of #316
