### ISSUE TITLE
Make the events module available in __init__.py

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#305]
This is a quality of life thing. Currently, if I write code like this:

    import ppb

    class Player(ppb.BaseSprite):
        def on_update(self, update: ppb.events.Update, signal):
            pass

PyCharm complains "Cannot find reference 'events' in '__init__.py'"

We can fix this by importing it explicitly in the init file.

**Comment by astronouth7303** [comment]
In general, we should probably put some thought into what we want to expose on `ppb`? I think I've mentioned that elsewhere...

**Comment by pathunstrom** [comment]
I'm mostly okay with "promote things as they become necessary". But we can open a discussion to figure out what the ppb name space should look like for an end user?
