### ISSUE TITLE
Can't slice BaseScene.

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#321]
I wanted to do 

`for s1, s2 in zip(scene, scene[1:]):`

This doesn't work, throws an attribute error that scene isn't subscriptable.

This is probably a functionality we want.

**Comment by astronouth7303** [comment]
Yes, we need to improve how node containers work to be more consistent with Python's collections.

I'm not sure subscription will work with anything other than Engine's scenes because I'm not sure anything else has a well-defined and obvious order.

**Comment by pathunstrom** [comment]
(I'm not sure which this counts as. It's kind of both.)

**Comment by pathunstrom** [comment]
We've decided this is as intended. Don't slice your scenes, it has no inherent meaning.
