### ISSUE TITLE
Drawing Primitives Assets

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#337]
The start of a massive change to the way PPB deals with rendering:

Instead of `Sprite.image = None` rendering a square, I'd like to provide an explicit API both for rendering the drawing primitives and defining their color, if they are an outline or a fill, and other such features.

Examples:

```
class SquareSprite(ppb.BaseSprite):
    image = ppb.primitives.Square(color=(255, 50, 50, 1), outline=None)
```

This square will be red, full opacity, and filled.

```
class CircleSprite(ppb.BaseSprite):
    image = ppb.primitives.Circle(color=(40, 255, 50, 0.5), outline=5)
```
This circle will be green, half opacity, and will have an outline of approximately 5 pixels when size 1.

```
class TriangleSprite(ppb.BaseSprite):
    image = ppb.primitives.Triangle(color=(0, 0, 0), outline=None)
```
A black triangle, filled.

Each shape is going to be a pseudo Asset.

**Comment by astronouth7303** [comment]
How do we want to handle mutation on these objects?

**Comment by pathunstrom** [comment]
My feeling is we should discourage mutation in general. That said, they're fairly cheap to create the low level asset for, so it can probably just create it new every frame.

**Comment by pathunstrom** [comment]
Thought I think opacity should be a metadata on the sprite and not at the asset level.

**Comment by astronouth7303** [comment]
PNG images (the preferred) have their own opacity.

I think sprite-level opacity is in the same category as tints and other post-processing effects?
