### ISSUE TITLE
Sides refactor

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#339]
Ok, a few things I'd like to do with sides:

* Replace `.left.top` etc with `.left_top` so that the whole thing is significantly less magical
* Make the sides API a general mixin, so its usable by camera and bounded scenes
* Use this as part of the camera-is-not-sprite rebuild

**Comment by astronouth7303** [comment]
(This means that there's going to need to introduce width/height as distinct things)

**Comment by pathunstrom** [comment]
The magic is so pretty, though. As long as we use full names with underscores (and not things like `midbottom`, sorry, Pygame) I'm okay blowing it up.

Agree with the second, I've been trying to convince myself to pull that trigger for a while, and yeah, it'll definitely go into the Camera eventually.

And yeah, probably, it's been on and off the table for over a year.

**Comment by astronouth7303** [comment]
I was just thinking replacing the dots with underscores. It'll be pretty tedious to write, but we can do that once.

**Comment by pathunstrom** [comment]
Yeah, that's totally fine, and yes, it's a bit of a rewrite, but it actually removes the need for Side all together.

**Comment by pathunstrom** [comment]
This will be done with the PR opened for #372
