### ISSUE TITLE
Example: Loading Screen

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#342]
We need a minimal example demonstrating how to use the loading screen feature (#336).

Should follow the new Documentation layout, the folder can just be named "loading_screen" or similar.

Any assets you need for your demo need to live in a resources folder next to your example.

You will want a number of art assets (I suggest 12+) (feel free to use anything already in the project, you may also release your own assets into ppb or use cc0 assets.)

**Comment by mfonism** [comment]
@pathunstrom has this been covered by https://github.com/ppb/pursuedpybear/tree/canon/examples/loading_screen?

**Comment by pathunstrom** [comment]
That looks like. I'll verify tonight and get back to you.

**Comment by pathunstrom** [comment]
Yes, that's definitely tied to this issue. Our asset loading is so much more performant that you never see the load bar, but I'm mostly going to shrug at that.

Closing this.
