### ISSUE TITLE
Race Condition when responding to SceneContinued

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#370]
I'll add a minimal example later, but throwing an update event in response to SceneContinued, then capturing that event to update sprites isn't working how I'd expect.

**Comment by astronouth7303** [comment]
@pathunstrom Do you still have this example?

**Comment by AstraLuma** [comment]
Hey, piper, I don't want to close this, but you need to write down an example?

**Comment by pathunstrom** [comment]
Right, I'll try to duplicate this soon.
