### ISSUE TITLE
Documentation: Fail to generate screen on Mac Mojave (PyGame)

### ISSUE THREAD

**Issue by CaseyFaist** [ppb/pursuedpybear#374]
When using Python 3.7 on Mojave, ppb will run but generate a blank window. 

This is not an issue with PPB itself, but will trip up a PPB user. The steps to unblock a user are not complicated - I resolved by using `pip3` and `python3` - but could be difficult to debug for programmers new to PyGame and unfamiliar with the problem. Problems they may face are what should they searching for, why do they need to specify python3 if their `.venv` specifies python 3.7 and the python repl successfully loads, etc.

Docs in a "Known Issues" section (either on readthedocs, here, or both) could help these users. 

Sources:

https://stackoverflow.com/questions/52718921/problems-getting-pygame-to-show-anything-but-a-blank-screen-on-macos-mojave

https://github.com/pygame/pygame/issues/555

**Comment by CaseyFaist** [comment]
I'm happy to write these docs if I can get some direction on where y'all would want them to live 😄

**Comment by astronouth7303** [comment]
To be clear: This is specifically an incompatibility with PyGame1 and MacOS Majove?

Sounds similar to the warnings we've been putting in our release notes about Python 3.8.

**Comment by astronouth7303** [comment]
Yes, a warning early in the docs would be good. The list of incompatibilities is getting long and I'm starting to get grumpy with PyGame as a project.

**Comment by astronouth7303** [comment]
Hopefully this will be fixed by #377/#387.

**Comment by astronouth7303** [comment]
Ok, with #387 merged, the underlying issues with this bug should be fixed?

**Comment by astronouth7303** [comment]
@pathunstrom @CaseyFaist this has been fixed on mac, right?

**Comment by pathunstrom** [comment]
I don't have a mojave mac to test on. But we should check on this.

**Comment by AstraLuma** [comment]
Can I get an update on this?

**Comment by AstraLuma** [comment]
We think this fixed itself and Mojave is about as dead as outsiders can tell.
