### ISSUE TITLE
run() should accept a scene as it's first argument

### ISSUE THREAD

**Issue by AstraLuma** [ppb/pursuedpybear#399]
Currently, `run()` only accepts a setup function as its first argument.

Also allow it to take a scene class or scene instance

**Comment by pathunstrom** [comment]
For whoever decides to pick this up:

The logic is basically check if it's an instance of BaseScene, then see if it's a type, then see if it's a callable. If all of this fails, helpful error message.

**Comment by pathunstrom** [comment]
I think this was solved with #516 

Going to verify today, and then maybe close this.

**Comment by AstraLuma** [comment]
This looks like it has not.

#516 handles `ppb.run(starting_scene=MyScene)` vs `ppb.run(starting_scene=MyScene())`

This issue is asking for `ppb.run(MyScene)` and `ppb.run(MyScene())` to also work.

**Comment by sheenarbw** [comment]
This seems to work just fine:

```
class MySpecialScene(ppb.Scene):
    def __init__(self):
        super().__init__()
        self.add(Player())


ppb.run(starting_scene=MySpecialScene())
```

And `BaseScene` doesn't seem to exist anywhere in the code...

Should this issue be closed? Maybe there's something I'm not understanding
