### ISSUE TITLE
Fix _rotation

### ISSUE THREAD

**Issue by AstraLuma** [ppb/pursuedpybear#403]
Currently, this doesn't work:

```python
class Thingy(Sprite):
    rotation = 90
```

This does:
```python
class Thingy(Sprite):
    _rotation = 90
```

Fix this.

**Comment by astronouth7303** [comment]
This was originally going to be fixed by #271.

**Comment by astronouth7303** [comment]
Kinda tempted to just leave off the the modulus logic?

IEEE double floats have 53 binary digits, so they can store up to decimal 9,007,199,254,740,992 before loosing precision. That would be 25 trillion full rotations before problems arose.

Somehow, I don't think that's something you'll see in the wild.

**Comment by pathunstrom** [comment]
Let's do it and fix it if people start hitting that limit.

**Comment by pathunstrom** [comment]
Throwing a quick checklist on this, since I think it's small enough and considered enough to go:

- [ ] Move overflow logic from `ppb.sprites.RotatableMixin.rotation` property to `ppb.sprites.RotatableMixin.rotate` method.
- [ ] Remove the `ppb.sprites.RotatableMixin.rotation` properties.
- [ ] Rename `ppb.sprites.RotatableMixin._rotation` attribute to `rotation`.
- [ ] Change `tests.test_sprites.test_rotatable_subclass` to set `rotation` instead of `_rotation`.

And as always, run the tests (including the viztests!).

**Comment by mark-boer** [comment]
I'll have a look at this issue :-) #pycascades2021

**Comment by mark-boer** [comment]
> Kinda tempted to just leave off the the modulus logic?
> 
> IEEE double floats have 53 binary digits, so they can store up to decimal 9,007,199,254,740,992 before loosing precision. That would be 25 trillion full rotations before problems arose.
> 
> Somehow, I don't think that's something you'll see in the wild.

You are slowly gonna start to lose precision before you reach that point. But you probably still need millions to billions of rotations before that becomes any serious issue.

**Comment by AstraLuma** [comment]
> You are slowly gonna start to lose precision before you reach that point. But you probably still need millions to billions of rotations before that becomes any serious issue.

I assume you're referring to the accumulated error of the billions of calculations, or that as you approach 53 binary digits, you'll loose the fractions needed to rotate at 60fps.

**Comment by mark-boer** [comment]
> I assume you're referring to the accumulated error of the billions of calculations, or that as you approach 53 binary digits, you'll loose the fractions needed to rotate at 60fps.

At some point e.g. the value is 1.000.000.000.000, the next closest value that can be represented by a float might be 1.000.000.000.002, so at stupidly large number you get weird rounding errors:

```
>>> a = 1e16
>>> a + 1
1e+16
```

**Comment by AstraLuma** [comment]
Right. And if your increment is 1deg, you shouldn't see that until the 2^53 (15.9 decimal digits, 1e16 as you wrote).
