### ISSUE TITLE
Remove Changelog from README

### ISSUE THREAD

**Issue by pradyunsg** [ppb/pursuedpybear#407]
The README still has "0.5.0" release notes, while ppb has now reached 0.8.0-beta. It'd be nice to either link to the releases page from the README or to update it to release notes for 0.8.0-beta.

Thanks for all the cool work y'all do! ^.^

**Comment by pathunstrom** [comment]
I'm pretty comfortable with removing those change notes and linking to the github releases page in its place. For the most part that's where we keep our change logs.

**Comment by astronouth7303** [comment]
We also copy the release notes to blog posts.
