### ISSUE TITLE
Update the docs homepage

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#409]
Currently, it's a stale copy of the README. As part of an attempt to improve the landing pages for various users, we should rewrite it.

The kinds of people who will be coming to our docs landing page (and caring about it) fall into two categories:

1. People who are directed there through one of our messaging platforms (ppb.dev, the twitter, or linked directly from inside the discord)
2. experienced developers who prefer going straight to the documentation.

As such, this needs to be able to assist these two groups as quickly as possible.

Functional outline:

1. Introduction: what is ppb, what problem is it trying to solve.
2. The structure of the documentation. Tell our users where the thing they might want to know is. (reference https://www.divio.com/blog/documentation/ for further details. Our documentation layout is based on this model.)
3. The next focus should be new users: Link directly to the getting started guide, explain what assumptions that guide has (you probably need to know how to program to really use our getting started guide.)
4. After that, focus on more experiences folks. They're going to be most interested in the cookbook and the API documentation. They want to solve specific problems. Explain how those are laid out, provide links.
5. At the end, standard TOC.

**Comment by astronouth7303** [comment]
People of many experience levels are going to be using all parts--whether it's "how can i do x" or "what are the args of y, again"

A large part of teaching programming is teaching how to search and how to read docs. So we should expect people I would not describe as "experienced" to be using the docs.

**Comment by pathunstrom** [comment]
Yes. But the last time you did more than scan the front (docs) page of a library you already know how to use?
