### ISSUE TITLE
Considering: Change Sprite to Actor

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#438]
The term Sprite is overloaded in game dev parlance, we'd like to reduce confusion by changing the Sprite class to Actor.

We would not change the underlying API and just like the BaseSprite -> Sprite we'll support the old name through a stub for two releases.

**Comment by astronouth7303** [comment]
I'm wondering about this:

Actor can imply rendering and non-rendering. With #229 and #128, we can define non-rendering game objects that do not inherit from `Sprite`. Given that, do we want Actors to be "game objects" or "stuff under the scene" and Sprites to be "visible things" (where Sprites are a kind of Actor)?

**Comment by AstraLuma** [comment]
#492 is mostly implemented at this point.

**Comment by pathunstrom** [comment]
Yeah, let's close this, was an interesting thought experience, but not sure we gain anything from this name.
