### ISSUE TITLE
Should be able to add new sprites during runtime without breaking dictionary view.

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#48]
```
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ppb/scenes.py", line 31, in simulate
    for group in self.groups.values():
RuntimeError: dictionary changed size during iteration
```

- [ ] Write test
- [ ] Resolve

**Comment by pathunstrom** [comment]
I've added good first issue because I _think_ this has been resolved. Write the test to prove it, and it's an easy contribution.

Basic idea:

1. Set up an Engine with a Updater and a Quitter
2. Have a sprite that spawns a copy of itself on_update
3. Confirm it doesn't throw an error
4. Double check the various states of the Engine:
    * That engine.current_scene has multiple sprites

**Comment by astronouth7303** [comment]
Is this still a bug? There's plenty of demos that do dynamic sprite spawning?

What is the dictionary view?

**Comment by astronouth7303** [comment]
I'm going to close this as the codebase has been rewritten several(?) times since this incarnation, so the bug has become nonsensical.

**Comment by pathunstrom** [comment]
I mean, I'd still like the tests, which is what this issue became.

**Comment by pathunstrom** [comment]
Also, dictionary view was an implementation detail of the old iteration behavior.
