### ISSUE TITLE
ppb.systems._sdl_utils should be public

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#495]
Trying to build a custom SDL subsystem for my game, and my linter is complaining because this is named privately. We probably want some of this to be exposed.

**Comment by AstraLuma** [comment]
ehhhhhhhhhhh..... like 3rd tier "exposed".

**Comment by pathunstrom** [comment]
Oh yeah, I'll be clear: Making this non-private but in the same place is enough. Like, this is absolutely an internal API, but will be used occasionally by advanced users.
