### ISSUE TITLE
Program does not load

### ISSUE THREAD

**Issue by Milan-Chicago** [ppb/pursuedpybear#497]
HI I get the following error:

WARNING:ppb.assetlib:File not found: 'ship.png'

When the program loads it loads with a blank screen. 

Please advise next steps?

**Comment by pathunstrom** [comment]
That warning is just a warning, you should still get a colored block.

If you're not, can you provide more information?

What OS are you on, which version of Python and ppb are you using?

Can you provide a screen shot of the blank screen? And could you share the code that made the blank screen?

**Comment by Milan-Chicago** [comment]
Yes, Hi thanks for the quick response.   Using windows 64, Python 3.7.4, please see below screen shots.

Thanks in advance,

Milan


[cid:71d51c17-a6a0-4b69-9109-0772066871bf]
[cid:145f6c46-5bba-48b8-98d1-a4447b27c3bc]
________________________________

**Comment by pathunstrom** [comment]
It seems your attachments did not make it through github. Could you upload directly to the issue here: https://github.com/ppb/pursuedpybear/issues/497 ?

**Comment by AstraLuma** [comment]
ping

**Comment by Milan-Chicago** [comment]
![pybear2](https://user-images.githubusercontent.com/7217067/86637309-ee2cbe80-bf9a-11ea-9c13-ddd4175a9b72.png)
![what rebels want](https://user-images.githubusercontent.com/7217067/86637322-f127af00-bf9a-11ea-8983-0d39be3a6e2c.jpg)

**Comment by pathunstrom** [comment]
Good news, that screen is just the default blank screen! So that's working. Are you sure you added the sprite the current scene? (A copy of your code would be helpful at this point.)

**Comment by Milan-Chicago** [comment]
code...
import ppb


class Ship(ppb.Sprite):

    def on_update(self, update_event, signal):
        self.position += 0, -(4 * update_event.time_delta)

def setup(scene):
    scene.add(Ship(pos=(0, 3.5)))

ppb.run(setup=setup)

**Comment by pathunstrom** [comment]
Try making the position in the scene.add (0, -3.5) and let me know if it shows up.

**Comment by Milan-Chicago** [comment]
Same, nothing yet.

**Comment by pathunstrom** [comment]
Going to take your code and test it on my machine. See if I can spot what's wrong. This is definitely odd.

**Comment by AstraLuma** [comment]
Ping

**Comment by AstraLuma** [comment]
Ping

**Comment by AstraLuma** [comment]
Closing due to the lack of activity >6mo
