### ISSUE TITLE
SDL flags must be passed bitwise -- prefer Pythonic APIs

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#50]
Right now, the `flags` parameter accepts a single flag, which must conform to the bitwise-OR flags from SDL/PyGame. Would much prefer that `flags` parameter accept either a single flag or an iterable of flags that will be combined for the user inside the engine.

- [ ] Define PPB Flags for supported flags.
- [ ] Consider that `flags` is an artifact of implementation and really is talking about rendering flags.
- [ ] Accept either a single flag or an iter of flags that can be bitwise-ORed inside the engine itself.
- [ ] Make lazy evaluation.

**Comment by imjennyli** [comment]
hey @pathunstrom, I'm thinking about taking this up, since I already did a newcomer issue :) 

I don't have any experience with game engines though -- can you explain what ` Define PPB Flags for supported flags.` means? are you asking for constants to be defined for each pygame supported flag?

**Comment by pathunstrom** [comment]
Yes, that's exactly what that step is for. 

At this time, that's going to be HWSURFACE and FULLSCREEN, which you can just import from pygame in a flags module and import them into `__init__.py` or you can determine the integer values of the flags and define them manually in `__init__.py with the appropriate values.

The first option is preferred because it is less likely to break based on changes to Pygame.

I am considering breaking each piece of this into it's own issue. Let me know if that'd make it easier for you?

**Comment by imjennyli** [comment]
@pathunstrom I'm indifferent as to whether you split it up or not -- if you don't mind doing multiple passes at the code review, leaving it as one is fine.
