### ISSUE TITLE
Set an image as the background

### ISSUE THREAD

**Issue by refaelsh** [ppb/pursuedpybear#510]
Hi,

Can you please help me, I wanna know how can I use an image as a background, and not just a single color.

Thanks. Refael.

**Comment by pathunstrom** [comment]
Currently the best way to do that is to make a large sprite whose image is your background and set it's layer to an arbitrarily low value. (Like `-10000`).

We have an issue for supporting a static background at the scene level, but haven't implemented it yet.

**Comment by refaelsh** [comment]
Thank you. I will close this issue.
