### ISSUE TITLE
Better error message when passing position and pos to a Sprite.

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#523]
Same as most of our error messages:

1. What went wrong
2. What you probably meant.
3. Suggestion on how to fix it.

If #522 is merged before this is complete, this is superseded by that.

Unlike that one, though, this can be done during v0.10.0 feature freeze.

**Comment by mfonism** [comment]
@pathunstrom can you please confirm that #543 closes #522, which in turn supersedes this issue, and therefore this issue can be closed?😃

**Comment by pathunstrom** [comment]
Yup, that killed the need for this. Closing!
