### ISSUE TITLE
Getting Started Guide: Install requirements for WSL2

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#526]
It has come to our attention that in order to run ppb under WSL2, you should follow the Ubuntu linux instructions.

We should include a `..note` directive in the windows instructions pointing to the linux ones for users of WSL2 as their platform.

**Comment by sjames1958gm** [comment]
Please, I can take this issue.

**Comment by pathunstrom** [comment]
Completed with #642
