### ISSUE TITLE
Docstrings systemslib.System

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#534]
Need docstrings for the System class.

Class docstring: All systems are context managers (consider linking to the context manager documentation in the python docs), note that they are GameObjects so can include children, and can be walked as part of the tree and respond to events.

Enter and exit docstrings: Just note these are provided to make sure all subclasses support the context manager protocol, but that should only be overridden if needed.

Related to #532

**Comment by qredwoods** [comment]
working on this at PyCascades 2024
