### ISSUE TITLE
Keyword only parameters in BaseScene

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#54]

**Comment by schamp** [comment]
I can take a stab at this.  It looks like the idea is to replace kwargs with 'background_color' as a keyword argument with a default value?

**Comment by pathunstrom** [comment]
Not necessarily replace kwargs, but to take the get() and turn it into a [keyword only argument](https://www.python.org/dev/peps/pep-3102/). Because of the nature of the API and the tendency to subclass APIs, I'd like to allow keywords to be passed arbitrarily to prevent breaking changes in the future.

**Comment by schamp** [comment]
That makes sense, I think I got it.
