### ISSUE TITLE
Add a Failer to test_signal

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#548]
Relevant test: https://github.com/ppb/pursuedpybear/blob/canon/tests/test_engine.py#L53

We need to add a Failer with a reasonable timeout to this test to prevent infinite loops causing CI time outs.

Failer defaults to 1 second, which is reasonable for most tests that will fail with it.

Import `ppb.testutils.Failer` and add it to the basic_systems in the test in question.

**Comment by MateusDenucci** [comment]
Just made a [pull request](https://github.com/ppb/pursuedpybear/pull/615) to fix it. Hopefully it is good (:
