### ISSUE TITLE
Add Failer to test_contexts

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#550]
Relevant test: https://github.com/ppb/pursuedpybear/blob/canon/tests/test_engine.py#L69

We need to add a Failer with a reasonable timeout to this test to prevent infinite loops causing CI time outs.

Failer defaults to 1 second, which is reasonable for most tests that will fail with it.

Import `ppb.testutils.Failer` and add it to the basic_systems in the test in question.

**Comment by sgavil** [comment]
Hi! Can I contribute to this issue?

**Comment by pathunstrom** [comment]
Yes, thank you!
