### ISSUE TITLE
Switch docs theme to furo

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#555]
#529 switched it from rtd to alabaster, and I'd rather we make a choice as official instead of up to whoever is working on the docs at the time.

Part of this may be hiring a designer to give us a basic identity for our websites that can be applied to ppb.dev and our docs websites.

If you have an opinion on what ppb should look for, here's where to get your voice in.

For the time being we aren't replacing Binny. I still quite like them.

**Comment by pradyunsg** [comment]
Hi! A bit of self-promotion: https://pradyunsg.me/furo/

:)

**Comment by AstraLuma** [comment]
@pathunstrom rather likes furo for a variety of structural and aesthetic reasons.

**Comment by elenajp** [comment]
Hi,

I would like to have a look into this one please.

Elena :)

**Comment by pathunstrom** [comment]
Feel free!

**Comment by AstraLuma** [comment]
Hey, @elenajp, how's this going?

**Comment by elenajp** [comment]
Hi @AstraLuma sorry for the late reply. Things have been busy at my end and I have a few interviews to prepare for. So feel free if you want to jump on this one. If you do, please keep me posted, as when I have some time again I could do it but yeah, go for it 😁
