### ISSUE TITLE
Design game pad interface for ppb

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#561]
Requires #559 and #560 to make experimentation possible.

The SDL documentation is thin, I found this tutorial which is a bit better: https://5pmcasual.com/post/sdl2-game-controllers/

Also, the SDL_GameControllerDatabase: https://github.com/gabomdq/sdl_gamecontrollerdb

We need to figure out how ppb surfaces the various parts of the controller lifecycle and how events should be best identified for user.

**Comment by AstraLuma** [comment]
Closing in favor of #447
