### ISSUE TITLE
Rename BaseScene

### ISSUE THREAD

**Issue by AstraLuma** [ppb/pursuedpybear#569]
It's still called `ppb.BaseScene` instead of `ppb.Scene`

why?

To Solve:

- [ ] Rename ppb.BaseScene to Scene in scenes.py
- [ ] Add a subclass of Scene called BaseScene with a deprecation warning (to be removed in 0.14 _or_ 1.0 whichever comes first.)
- [ ] Import Scene into `__init__.py`
- [ ] Update tests to use ppb.Scene

**Comment by pathunstrom** [comment]
Legacy. (We should totally change this.)

**Comment by pathunstrom** [comment]
Completed with #583
