### ISSUE TITLE
ImportError: could not find any library for SDL2_gfx (PYSDL2_DLL_PATH: unset)

### ISSUE THREAD

**Issue by jugmac00** [ppb/pursuedpybear#580]
Hi,

I just read about pbb on Twitter (https://twitter.com/pursuedpybear/status/1363252329441488896 ) and wanted to give it a quick try.

I created a virtualenv with Python 3.6, installed pbb, and run the example from here ( https://github.com/ppb/pursuedpybear#try-it ) and got the following traceback.

```
/tmp/try-pbb via 🐍 v3.6.9 (venv) 
❯ python main.py 
Traceback (most recent call last):
  File "/tmp/try-pbb/venv/lib/python3.6/site-packages/sdl2/sdlgfx.py", line 43, in <module>
    os.getenv("PYSDL2_DLL_PATH"))
  File "/tmp/try-pbb/venv/lib/python3.6/site-packages/sdl2/dll.py", line 105, in __init__
    (libinfo, dllmsg))
RuntimeError: could not find any library for SDL2_gfx (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import ppb
  File "/tmp/try-pbb/venv/lib/python3.6/site-packages/ppb/__init__.py", line 39, in <module>
    from ppb.assets import Circle
  File "/tmp/try-pbb/venv/lib/python3.6/site-packages/ppb/assets.py", line 13, in <module>
    from sdl2.sdlgfx import (
  File "/tmp/try-pbb/venv/lib/python3.6/site-packages/sdl2/sdlgfx.py", line 45, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2_gfx (PYSDL2_DLL_PATH: unset)
```

I run Ubuntu 18.04.

Is there anything else I need to install?

Thank you!

**Comment by AstraLuma** [comment]
Yup! SDL itself. (You only need to do this for Linux.)

Instructions are towards the end of https://ppb.readthedocs.io/en/stable/getting-started.html#installing-ppb

See also https://github.com/a-hurst/pysdl2-dll/issues/2

**Comment by jugmac00** [comment]
Thanks for the quick feedback! The suggested solution works like a charm.

I created a PR to add a sentence about the additional packages to the `Try it` section.

P.S.: Crossing fingers that there will be wheels in future also for Linux!

**Comment by pathunstrom** [comment]
We rely on pysdl2-dll for our SDL dlls, I believe the maintainer of that project is open to assistance for making it happen/! (And we do want linux wheels eventually!)
