### ISSUE TITLE
Third triangle in viztest is mislabeled

### ISSUE THREAD

**Issue by AstraLuma** [ppb/pursuedpybear#599]
In `viztests/main.py`, it labels the third triangle as equilateral, which is incorrect.

Also, `main.py` is a terrible name for that test.

**Comment by abhijeetgupto** [comment]
assign this to me , i'll do it !

**Comment by ProsperousHeart** [comment]
@AstraLuma what is it supposed to be? What do you suggest the test file name be?

**Comment by AstraLuma** [comment]
not a file name, inside it calls equalateral when i think it's Isosceles

**Comment by lunacodes** [comment]
Closing. Was completed in https://github.com/ppb/pursuedpybear/pull/638
