### ISSUE TITLE
Add docstring to vector.Vector

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#60]
Copy from ppb_vector or write a new one.

**Comment by dhyanpatel** [comment]
Where can I find ppb_vector?

**Comment by Olorimor** [comment]
If no one has taken a stab at it, I can give it a shot.

**Comment by pathunstrom** [comment]
Sure, read up on docstrings at [PEP257](https://www.python.org/dev/peps/pep-0257/) to get the style right.

**Comment by astronouth7303** [comment]
FYI, this is now https://github.com/ppb/ppb-vector/blob/master/ppb_vector/vector2.py

**Comment by astronouth7303** [comment]
Closing this, since a _lot_ of work has gone into ppb-vector, including docstrings.
