### ISSUE TITLE
Add helpful error when translate_point_to_screen fails due to AttributeError

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#612]
Example Error:

```
File "camera.py", line 163, in translate_point_to_screen
    return Vector(point.x - self.left, self.top - point.y) * self.pixel_ratio
AttributeError: 'tuple' object has no attribute 'x'
```

We don't necessarily want to force folks to use the ppb vector class, but we do expect the vector.x and vector.y to exist. That said, for people experiencing this error, they most likely set the position of a gameobject to a tuple or some other representation of a vector instead of a Vector.

We should capture this attribute error and raise a new one with a more helpful message. Encourage users to look at the Vector class and to set the position attribute using it instead of a tuple, list, or dictionary.

**Comment by AstraLuma** [comment]
This is basically the same problem as `_rotation` and what #271 tried to solve.
