### ISSUE TITLE
Add instruction to do an editable install to the CONTRIBUTING.md

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#613]
Right now we don't explain doing an editable install of ppb in the I Want To Code section of the CONTRIBUTING file. We should include that instruction for people newer to Python contributing.

**Comment by elenajp** [comment]
Hello! 

I am new to open source and I would love the opportunity to contribute with this issue. 

Elena :)

**Comment by elenajp** [comment]
I submitted a pull request :)

**Comment by lunacodes** [comment]
Closing, since it was completed in [e58233ebd1109463e44a383af104602a26d5d08f]
