### ISSUE TITLE
Add docstrings to sprites.Side

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#62]

**Comment by pvtuan10** [comment]
Hi @pathunstrom, I would like to work on this.

**Comment by Duxy1996** [comment]
This is my first time doing a contribution with docstrings. I have been programming in python but i have never had the chance of contributing. If you let me I would like to try to do the docstring for sprites.Side following the PEP 257 convention.
Thanks, duxy1996

**Comment by pathunstrom** [comment]
Being closed in favor of removing the Sides API. #339
