### ISSUE TITLE
Add docstrings to scenes.BaseScene

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#63]

**Comment by pvtuan10** [comment]
Hi @pathunstrom, I would like to work on this.

**Comment by schamp** [comment]
I can take a stab at this one.

**Comment by schamp** [comment]
whoops, looks like somebody's already got it: https://github.com/ppb/pursuedpybear/pull/71

**Comment by pathunstrom** [comment]
Closing this. Things have shifted enough that there's been a lot of drift.
