### ISSUE TITLE
Add docstrings to engine.GameEngine

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#64]

**Comment by ali-alsabbah** [comment]
I'm interested in doing this if it's still open, but I might need a little guidance

**Comment by pathunstrom** [comment]
Basics of docstrings is in [pep 257](https://www.python.org/dev/peps/pep-0257/).

So, for an example of what I'm looking for as "best": Check out [the scenes module](https://github.com/ppb/pursuedpybear/blob/master/ppb/scenes.py) for a sample.

If you just want the commit, I'll take even basic docstrings.

**Comment by pathunstrom** [comment]
Resolved with #423
