### ISSUE TITLE
ppb.events `__all__` don't include all event types

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#648]
Mostly affects tooling, but we should include the missing events in the events `__all__`.

Noticed this in PyCharm when importing KeyPressed, looks like we're missing both Key events and the Mouse events, but should be a quick process of confirming which events are exported.

**Comment by phileinsophos** [comment]
can I work on this

**Comment by AstraLuma** [comment]
Yeah, go ahead

**Comment by pathunstrom** [comment]
Closed via #649
