### ISSUE TITLE
features subpackage doesn't have __init__.py

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#669]
It's not strictly necessary, but some tools don't recognize it as a package. Let's add a basic one ~~with imports of the subsidiary modules.~~

**Comment by AstraLuma** [comment]
I think we deliberately don't proactively import the submodules, for efficiency and such.

**Comment by moshez** [comment]
Agreed with @AstraLuma -- adding just the file (with a docstring) is probably enough to solve the recognition problem, without changing behavior in weird edge cases.

**Comment by pathunstrom** [comment]
Striking the import portion of the ticket!
