### ISSUE TITLE
Update Getting Started

### ISSUE THREAD

**Issue by ProsperousHeart** [ppb/pursuedpybear#671]
![image](https://user-images.githubusercontent.com/20706498/152704216-d978df6e-5b0f-40a7-bacf-76a583cdba00.png)
From [Getting Started](https://ppb.dev/contributing.html) there are a couple of things that might be confusing to newbies:

1. It is a bit confusing to say "find a ticket you want to work on and create a PR with just your name changed in contributions." For one, newbies may not know what PR stands for. (Or maybe I don't understand the "WIP" part?) For another, people may just do that and then never complete the issue they said they wanted to work on.
2. Is the code that has the **git clone** command for a unix machine? (I never have to do that source part on a Windows machine.)
3. The code section has people doing a clone of the main repo and not their fork,

![image](https://user-images.githubusercontent.com/20706498/152704675-5022fc0d-314a-4c3f-a1f8-3dfee4e84d7e.png)
Also found that the line to install requirements is missing an s

**Comment by AstraLuma** [comment]
1. Good catch! That is confusing to newbies and we should explain it more.
2. On Unixy boxen, git generally just exists if it's installed. No extra steps are needed to enable it. ("generally" because there's no end of people doing weird things with their Linux.)
3. Yup! That is also wrong and in needing of fixing.

**Comment by ProsperousHeart** [comment]
Adding another item:  requirements file is missing an s (it is below the numbered values)

**Comment by ProsperousHeart** [comment]
also - we may want to have a section for Windows installations for people like myself :)

**Comment by AstraLuma** [comment]
Yup! We have some of that in the installation doc.

(TODO: sphinx extension for platform-specific tabs.)

**Comment by ProsperousHeart** [comment]
Oh great! It would be helpful for Windows users to have that linked in the doc
