### ISSUE TITLE
SDLmixererror when invoking ppb.run()

### ISSUE THREAD

**Issue by ace510** [ppb/pursuedpybear#674]
consistently when I invoke ppb.run() it immediately throws a

ppb.systems.sdl_utils.SdlMixerError: Error calling Mix_Init: Failed loading ModPlug_Tell: The specified procedure could not be found.
error

**Comment by pathunstrom** [comment]
This is due to a new dependency release. We'll resolve it before the next ppb release, but in the short term if you EDITED: `pip install --upgrade pysdl-dll==2.0.20` you should be able to use it until it's all sorted.

**Comment by ace510** [comment]
sadly, gave that a shot, getting 
`(venv) PS C:\Users\ihclark\python-2022\Python-2022-9-30> pip install --upgrade pysdl-dll==2.022
ERROR: Could not find a version that satisfies the requirement pysdl-dll==2.022 (from versions: none)
ERROR: No matching distribution found for pysdl-dll==2.022`

**Comment by pathunstrom** [comment]
I typoed that very badly: `pysdl2-dll==2.0.20`. I tested this for a tutorial recently and it continues to work. Sorry about the misinformation.

**Comment by ace510** [comment]
bless 👼🏻 worked a treat!
