### ISSUE TITLE
RectangleSprite objects create a Square image as default.

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#691]
Probably need to special case our default asset creation to create an appropriately shaped rectangle instead of a square.

Sample code:

```python
import ppb


class Platform(ppb.RectangleSprite):
    pass


def setup(scene):
    scene.add(Platform(width=3, height=1, position=ppb.Vector(0, -5)))
```

We end up with a square of size 3 instead of a rectangle with a 3:1 aspect ratio.

![image](https://github.com/ppb/pursuedpybear/assets/6393101/1f134446-2ebb-4951-94a9-2d4532d2dccd)

What it should look like:

![image](https://github.com/ppb/pursuedpybear/assets/6393101/644a842b-594e-4e0b-b007-def2c19c583c)

Noting, this currently gets set in the asset (https://github.com/ppb/pursuedpybear/blob/canon/ppb/systems/renderer.py#L93-L107) and would require some refactoring to make it possible to contextually choose the asset definition.

**Comment by davidism** [comment]
I'm working on this at the PyCascades 2024 sprint!
