### ISSUE TITLE
KeyBoardMovementSprite moves too quickly when moving diagonally

### ISSUE THREAD

**Issue by sheenarbw** [ppb/pursuedpybear#709]
The new KeyBoardMovementSprite handles up, down, left and right movements fine, but if you move diagonally it moves much faster.

**Comment by AstraLuma** [comment]
Would you say approximately 40% faster?

Yup, looks like the code fell into one of the classic blunders: increased speed due to hypotenuse.

**Comment by AstraLuma** [comment]
`ppb.features.default_sprites.KeyBoardMovementSprite` does not normalize its direction vector before applying it to the movement equation.

There are methods in the `Vector` to perform this normalization.

**Comment by AstraLuma** [comment]
Also, keep in mind that the zero vector may explode in the math, so you may need to special case that.
