### ISSUE TITLE
New Log Levels for low level engine debugging

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#82]
Right now, it is impossible to add debug logging to the Engine itself at the `logging.DEBUG` level without it flooding a user's debug logging.

To prevent this, some sort of mechanism should be added to allow engine logging to use a level lower than the built in `logging.DEBUG`

To that end, a new [logger class could be implemented](https://stackoverflow.com/a/22586200/2653506).

Alternatively we can monkey-patch `logging` to have an additional method.

Or finally we could, as developers on the engine proper, use the "hard" way of calling `logging.log(NEW_LEVEL, debug_message)` directly.

Additionally, we should pick a logging value to use.

**Comment by pathunstrom** [comment]
Before any other participation, we should default the new log level to 5, halfway down from the default `DEBUG` level. That allows us to add additional logging levels on both sides as needed.

**Comment by astronouth7303** [comment]
Would it be better to use logging levels or logging channels (logger names)? Like, the general logging level is `DEBUG` but anything from `ppb.*` is `WARNING`.

**Comment by pathunstrom** [comment]
Closing as there are better solutions to better logging detail.
